- name: Create namespace
  vars: 
    ansible_python_interpreter: "/usr/bin/python3"
  k8s:
    definition:
      kind: Namespace
      apiVersion: v1
      metadata:
        name: "{{ app_namespace }}"

- name: Deploy App 
  k8s: 
    definition: "{{ lookup('template', 'app_template.yml.j2') }}"
    namespace: "{{ app_namespace }}"