# Este sera el playbook de Ansible que se ejecuta para configurar los recurso.
# Por un lado, se configura Python, ACR y las aplicaciones,
# y por otro lado, se configura el servidor web.
---
- name: Python, ACR, Apps
  hosts: localhost
  connection: local
  vars_files:
    - credentials.yml
    - constants.yml

  roles:
    - python
    - acr
    - app

#Se conf
- name: Webserver
  hosts: localhost
  remote_user: "{{ ssh_remote_user }}"
  vars_files:
    - credentials.yml
    - constants.yml
  roles:
    - webserver
