---
- name: Python, ACR, Apps
  hosts: localhost
  connection: local
  become: yes
  vars_files:
    - credentials.yml
    - constants.yml

  roles:
    - python
    - acr
    - app

- name: Webserver
  hosts: localhost
  become: yes
  remote_user: "{{ ssh_remote_user }}"
  vars_files:
    - credentials.yml
    - constants.yml
  roles:
    - webserver
